name: Monitor Regulations.gov comments

on:
  schedule:
    # At minute 0 of every hour
    - cron: '0 * * * *'
  workflow_dispatch:        # allow manual runs too

jobs:
  poll:
    runs-on: ubuntu-latest
    env:
      WEBSITE_URL:    ${{ secrets.WEBSITE_URL }}
      EMAIL_USER:     ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      RECIPIENT:      ${{ secrets.RECIPIENT }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # Restore the small state file so we remember whether the box was seen
      - name: Restore state
        uses: actions/cache@v4
        with:
          path: state.json
          key: monitor-comments-state

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor
        run: python monitor_comments.py

      # Save updated state.json for the next invocation
      - name: Save state
        uses: actions/cache@v4
        with:
          path: state.json
          key: monitor-comments-state
